name: CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: composer

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install PHP dependencies
        run: composer i

      - name: Lint files
        run: composer run-script lint

      - name: Analyze files
        run: composer run-script analyze

  test:
    name: Test PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: [ '8.0', '7.4', '7.3', '7.2' ]
        os: [ ubuntu-latest ]
        experimental: [ false ]
        coverage: [ false ]
        include:
          - php: '7.4'
            os: ubuntu-latest
            experimental: false
            coverage: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set PHP_COVERAGE
        run: |
          if [ ${{ matrix.coverage }} == 'true' ]; then
            echo "PHP_COVERAGE=xdebug" >> $GITHUB_ENV
          else
            echo "PHP_COVERAGE=none" >> $GITHUB_ENV
          fi

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ env.PHP_COVERAGE }}
          tools: composer

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-composer-

      - name: Install PHP dependencies
        run: composer i

      - name: Run tests
        run: composer run-script test

      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v1
