name: CI

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          coverage: none
          tools: composer

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Lint files
        run: composer run-script lint

      - name: Analyze files
        run: composer run-script analyze

  test:
    name: Test PHP ${{ matrix.php }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: [ '8.0', '7.4', '7.3', '7.2' ]
        os: [ ubuntu-latest ]
        experimental: [ false ]
        include:
          - php: '7.4'
            os: ubuntu-latest
            experimental: false
            coverage: true

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ matrix.coverage && 'xdebug' || 'none' }}
          tools: composer

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: composer run-script test

      - name: Upload coverage to Codecov
        if: ${{ matrix.coverage }}
        uses: codecov/codecov-action@v2
